"""Contest-faithful dev agent environment for 'shlepa run' (container mode).

The real contest runs the agent INSIDE the task environment container,
which is built FROM secureintelligent/acp (pydantic-ai, logfire and the
OpenTelemetry SDK/OTLP exporters are already baked in there). For dev
runs we build a wrapper image on top of the task environment image:

1. stage the shlepa_agent package (telemetry included) into /agent/
2. install the OpenInference enrichment package into the acp venv
   (build-time only; the runtime stays fully offline)

The agent then runs in the same container via ``docker exec`` with
``LOCAL_AGENT_WORKDIR=/app``, and telemetry reaches the host OTLP
collector over host networking (localhost:4318) without internet.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

METRICS_MARKER = "SLEPA_AGENT_METRICS_JSON="

#: Version pinned to agent/uv.lock (build-time install in the dev image).
OPENINFEERENCE_PIN = "openinference-instrumentation-pydantic-ai==0.1.22"

#: Source of the dev entrypoint baked into the dev image at /agent/dev_run.py.
DEV_RUN_SOURCE = r'''"""Dev entrypoint for the shlepa agent running INSIDE the task container.

Generated by shlepa_cli.dev_env and baked into the dev image. Not part
of the submission (run.sh is the submission entrypoint). Reads the
prompt from argv[1], runs the agent against LOCAL_AGENT_WORKDIR, prints
the final answer to stdout and reports usage as a
'SLEPA_AGENT_METRICS_JSON=...' line on stderr.
"""

import asyncio
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, "/agent")

from shlepa_agent import core  # noqa: E402

METRICS_MARKER = "SLEPA_AGENT_METRICS_JSON="


def _workdir() -> Path:
    raw = os.environ.get("LOCAL_AGENT_WORKDIR")
    return Path(raw).resolve() if raw else Path.cwd().resolve()


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: dev_run.py <prompt>", file=sys.stderr)
        return 2
    prompt = sys.argv[1]
    try:
        timeout = int(os.environ.get("SLEPA_AGENT_TIMEOUT", "0") or 0) or None
    except ValueError:
        timeout = None
    otel = os.environ.get("SLEPA_OTEL_ENABLED") == "1"
    provider = None
    if otel:
        from shlepa_agent.telemetry import configure

        provider = configure()
    try:
        agent = core.get_pydantic_agent(instrument=otel)
        try:
            result = asyncio.run(
                asyncio.wait_for(
                    agent.run(
                        prompt, deps=core.LocalAgentDeps(workdir=_workdir())
                    ),
                    timeout=timeout,
                )
            )
        except asyncio.TimeoutError:
            print(f"agent timed out after {timeout}s", file=sys.stderr)
            return 1
        usage = result.usage
        metrics = {
            "final_output": str(result.output),
            "tokens_in": int(usage.input_tokens or 0) if usage else 0,
            "tokens_out": int(usage.output_tokens or 0) if usage else 0,
            "tool_calls": int(usage.tool_calls or 0) if usage else 0,
        }
        print(metrics["final_output"])
        print(METRICS_MARKER + json.dumps(metrics), file=sys.stderr)
        return 0
    finally:
        if provider is not None:
            provider.shutdown()


if __name__ == "__main__":
    raise SystemExit(main())
'''


def stage_agent(context_dir: Path, agent_dir: Path) -> Path:
    """Copy the shlepa_agent package into ``context_dir/dev_agent/``.

    Telemetry IS included (dev images are local-only; the submission
    zip excludes it). run.sh / agent.py / tests / pyproject are not
    part of the in-container agent.
    """
    context_dir = Path(context_dir)
    agent_dir = Path(agent_dir)
    package = context_dir / "dev_agent" / "shlepa_agent"
    package.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        agent_dir / "shlepa_agent",
        package,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
    )
    (context_dir / "dev_agent" / "dev_run.py").write_text(DEV_RUN_SOURCE)
    return context_dir / "dev_agent"


def write_dev_dockerfile(context_dir: Path, env_image: str) -> Path:
    """Write the dev wrapper Dockerfile (FROM the task env image)."""
    dockerfile = Path(context_dir) / "Dockerfile"
    dockerfile.write_text(
        f"FROM {env_image}\n"
        "COPY dev_agent/ /agent/\n"
        f"RUN /app/.venv/bin/uv pip install --python /app/.venv/bin/python "
        f"{OPENINFEERENCE_PIN}\n"
    )
    return dockerfile


def build_dev_image(
    docker,
    *,
    env_image: str,
    dev_image: str,
    agent_dir: Path,
    workdir: Path,
) -> str:
    """Stage the agent into a build context and build ``dev_image``.

    The context lives under ``workdir/dev-build`` (kept around for
    debugging; rebuilt from scratch on every call).
    """
    context = Path(workdir) / "dev-build"
    if context.exists():
        shutil.rmtree(context)
    context.mkdir(parents=True, exist_ok=True)
    stage_agent(context, agent_dir)
    write_dev_dockerfile(context, env_image)
    docker.build(dev_image, context)
    return dev_image


def parse_agent_metrics(stderr: str) -> dict:
    """Parse the SLEPA_AGENT_METRICS_JSON marker from agent stderr.

    Returns a dict with final_output / tokens_in / tokens_out /
    tool_calls; defaults to empty values when the marker is missing or
    broken (the run still counts as an unsolved, not a crash).
    """
    defaults = {
        "final_output": "",
        "tokens_in": 0,
        "tokens_out": 0,
        "tool_calls": 0,
    }
    for line in reversed((stderr or "").splitlines()):
        line = line.strip()
        if not line.startswith(METRICS_MARKER):
            continue
        try:
            data = json.loads(line[len(METRICS_MARKER):])
            result = dict(defaults)
            for key in defaults:
                if key in data:
                    result[key] = data[key]
            return result
        except (json.JSONDecodeError, TypeError):
            return dict(defaults)
    return dict(defaults)
