"""Contest-faithful dev agent environment for 'shlepa run' (container mode).

The real contest runs the agent INSIDE the task environment container,
which is built FROM secureintelligent/acp (pydantic-ai, logfire and the
OpenTelemetry SDK/OTLP exporters are already baked in there). For dev
runs we build a wrapper image on top of the task environment image:

1. stage the shlepa_agent package (telemetry included) into /agent/
2. install the OpenInference enrichment package into the acp venv
   (build-time only; the runtime stays fully offline)

The agent then runs in the same container via ``docker exec`` with
``LOCAL_AGENT_WORKDIR=/app``, and telemetry reaches the host OTLP
collector over host networking (localhost:4318) without internet.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

METRICS_MARKER = "SLEPA_AGENT_METRICS_JSON="

#: Version pinned to agent/uv.lock (build-time install in the dev image).
OPENINFEERENCE_PIN = "openinference-instrumentation-pydantic-ai==0.1.22"

#: Source of the dev entrypoint baked into the dev image at /agent/dev_run.py.
DEV_RUN_SOURCE = r'''"""Dev entrypoint for the shlepa agent running INSIDE the task container.

Generated by shlepa_cli.dev_env and baked into the dev image. Not part
of the submission (run.sh is the submission entrypoint). Reads the
prompt from argv[1], runs the budgeted v1 agent (core.run_prompt: the
main phase plus the commit phase when the budget runs out) against
LOCAL_AGENT_WORKDIR, prints the final answer to stdout and reports
usage as a 'SLEPA_AGENT_METRICS_JSON=...' line on stderr.
"""

import asyncio
import json
import logging
import os
import sys

sys.path.insert(0, "/agent")

from shlepa_agent import core  # noqa: E402

METRICS_MARKER = "SLEPA_AGENT_METRICS_JSON="

# v1 main-phase status -> engine termination reason
_TERMINATION = {"done": "ok", "budget": "budget", "error": "error"}


class _MetricsCapture(logging.Handler):
    """Collect run metrics from the agent's JSON event log.

    The v1 core logs a ``usage`` event with cumulative tokens after each
    model request, a ``llm_tool_call`` event per tool invocation, and a
    final ``agent_done`` carrying the main-phase status.
    """

    def __init__(self) -> None:
        super().__init__()
        self.tokens_in = 0
        self.tokens_out = 0
        self.tool_calls = 0
        self.status: str | None = None

    def emit(self, record: logging.LogRecord) -> None:
        try:
            data = json.loads(record.getMessage())
        except (TypeError, ValueError):
            return
        event = data.get("event")
        if event == "usage":
            self.tokens_in = int(data.get("cumulative_input") or 0)
            self.tokens_out = int(data.get("cumulative_output") or 0)
        elif event == "llm_tool_call":
            self.tool_calls += 1
        elif event == "agent_done":
            self.status = data.get("status")


def _run_agent(prompt: str, timeout, otel: bool) -> int:
    core._configure_logging()
    capture = _MetricsCapture()
    core.LOGGER.addHandler(capture)
    try:
        output = asyncio.run(
            asyncio.wait_for(core.run_prompt(prompt, instrument=otel), timeout=timeout)
        )
    except asyncio.TimeoutError:
        # wait_for expired: report a termination=timeout marker so the
        # engine can distinguish a clean timeout from a crash, and stamp
        # the root span so the exported trace shows the same reason.
        if otel:
            try:
                from shlepa_agent.telemetry import mark_termination

                mark_termination("timeout")
            except Exception:  # telemetry must never break the run
                pass
        print(f"agent timed out after {timeout}s", file=sys.stderr)
        print(
            METRICS_MARKER
            + json.dumps(
                {
                    "final_output": "",
                    "tokens_in": capture.tokens_in,
                    "tokens_out": capture.tokens_out,
                    "tool_calls": capture.tool_calls,
                    "termination": "timeout",
                }
            ),
            file=sys.stderr,
        )
        return 1
    except Exception as exc:  # noqa: BLE001 - stamp the reason, re-raise
        # Crash: stamp the root span with the exception class so the
        # exported trace carries the same 'crash:<Exc>' reason that ends
        # up in result.json, then re-raise for a non-zero exit.
        if otel:
            try:
                from shlepa_agent.telemetry import mark_termination

                mark_termination(f"crash:{type(exc).__name__}")
            except Exception:  # telemetry must never break the run
                pass
        raise
    metrics = {
        "final_output": output,
        "tokens_in": capture.tokens_in,
        "tokens_out": capture.tokens_out,
        "tool_calls": capture.tool_calls,
        "termination": _TERMINATION.get(capture.status, "ok"),
    }
    if output:
        print(output)
    print(METRICS_MARKER + json.dumps(metrics), file=sys.stderr)
    return 0


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: dev_run.py <prompt>", file=sys.stderr)
        return 2
    prompt = sys.argv[1]
    try:
        timeout = int(os.environ.get("SLEPA_AGENT_TIMEOUT", "0") or 0) or None
    except ValueError:
        timeout = None
    otel = os.environ.get("SLEPA_OTEL_ENABLED") == "1"
    provider = None
    if otel:
        from shlepa_agent.telemetry import configure

        provider = configure()
    try:
        if provider is not None:
            # Root span for the whole run; carries the task slug so
            # traces can be grouped per task in Jaeger.
            from shlepa_agent.telemetry import root_span

            with root_span(provider):
                return _run_agent(prompt, timeout, otel)
        return _run_agent(prompt, timeout, otel)
    finally:
        if provider is not None:
            provider.shutdown()


if __name__ == "__main__":
    raise SystemExit(main())
'''


def stage_agent(context_dir: Path, agent_dir: Path) -> Path:
    """Copy the shlepa_agent package + tools/ into ``context_dir/dev_agent/``.

    Telemetry IS included (dev images are local-only; the submission
    zip excludes it). run.sh / agent.py / tests / pyproject are not
    part of the in-container agent. The tools/ helper scripts (e.g.
    tools/recon.py) land at /agent/tools/ inside the container, matching
    the /agent/... path the system prompt falls back to.
    """
    context_dir = Path(context_dir)
    agent_dir = Path(agent_dir)
    package = context_dir / "dev_agent" / "shlepa_agent"
    package.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        agent_dir / "shlepa_agent",
        package,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
    )
    tools_src = agent_dir / "tools"
    if tools_src.is_dir():
        shutil.copytree(
            tools_src,
            context_dir / "dev_agent" / "tools",
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
        )
    (context_dir / "dev_agent" / "dev_run.py").write_text(DEV_RUN_SOURCE)
    return context_dir / "dev_agent"


def write_dev_dockerfile(context_dir: Path, env_image: str) -> Path:
    """Write the dev wrapper Dockerfile (FROM the task env image)."""
    dockerfile = Path(context_dir) / "Dockerfile"
    dockerfile.write_text(
        f"FROM {env_image}\n"
        "COPY dev_agent/ /agent/\n"
        f"RUN /app/.venv/bin/uv pip install --python /app/.venv/bin/python "
        f"{OPENINFEERENCE_PIN}\n"
    )
    return dockerfile


def build_dev_image(
    docker,
    *,
    env_image: str,
    dev_image: str,
    agent_dir: Path,
    workdir: Path,
) -> str:
    """Stage the agent into a build context and build ``dev_image``.

    The context lives under ``workdir/dev-build`` (kept around for
    debugging; rebuilt from scratch on every call).
    """
    context = Path(workdir) / "dev-build"
    if context.exists():
        shutil.rmtree(context)
    context.mkdir(parents=True, exist_ok=True)
    stage_agent(context, agent_dir)
    write_dev_dockerfile(context, env_image)
    docker.build(dev_image, context)
    return dev_image


def _has_metrics_marker(stderr: str) -> bool:
    return any(
        line.strip().startswith(METRICS_MARKER)
        for line in (stderr or "").splitlines()
    )


class AgentCrashError(RuntimeError):
    """The agent container exited non-zero without a metrics marker.

    Carries the exit code so the engine can tell an OOM kill (137) from
    a plain crash.
    """

    def __init__(self, message: str, returncode: int | None = None):
        super().__init__(message)
        self.returncode = returncode


def run_agent_in_container(
    docker,
    container: str,
    prompt: str,
    env: dict[str, str],
    timeout_sec: int | None = None,
):
    """Run /agent/dev_run.py inside the container and parse the outcome.

    ``env`` is the docker-exec environment (model, workdir, timeout,
    telemetry). A hard exec timeout is the agent timeout plus a 120s
    buffer; a non-zero exit without the metrics marker is a crash and
    raises RuntimeError (the engine records it as a hard error).
    """
    from shlepa_cli.run_engine import AgentRun

    exec_timeout = timeout_sec + 120 if timeout_sec else None
    proc = docker.exec(
        container,
        ["/app/.venv/bin/python", "/agent/dev_run.py", prompt],
        dict(env),
        timeout=exec_timeout,
    )
    metrics = parse_agent_metrics(proc.stderr or "")
    if proc.returncode != 0 and not _has_metrics_marker(proc.stderr or ""):
        tail = (proc.stderr or proc.stdout or "")[-1000:]
        raise AgentCrashError(
            f"agent exited with code {proc.returncode}: {tail}",
            returncode=proc.returncode,
        )
    return AgentRun(
        final_output=metrics["final_output"] or (proc.stdout or "").strip(),
        tokens_in=metrics["tokens_in"],
        tokens_out=metrics["tokens_out"],
        tool_calls=metrics["tool_calls"],
        termination=metrics["termination"],
    )


def parse_agent_metrics(stderr: str) -> dict:
    """Parse the SLEPA_AGENT_METRICS_JSON marker from agent stderr.

    Returns a dict with final_output / tokens_in / tokens_out /
    tool_calls / termination; defaults to empty values and
    termination='ok' when the marker is missing or broken (the run
    still counts as an unsolved, not a crash).
    """
    defaults = {
        "final_output": "",
        "tokens_in": 0,
        "tokens_out": 0,
        "tool_calls": 0,
        "termination": "ok",
    }
    for line in reversed((stderr or "").splitlines()):
        line = line.strip()
        if not line.startswith(METRICS_MARKER):
            continue
        try:
            data = json.loads(line[len(METRICS_MARKER):])
            result = dict(defaults)
            for key in defaults:
                if key in data:
                    result[key] = data[key]
            return result
        except (json.JSONDecodeError, TypeError):
            return dict(defaults)
    return dict(defaults)
