"""MITRE ATT&CK knowledge-base engine (read-only, stdlib-only, offline).

The KB artifact lives in ``shlepa_agent/kb/`` (generated by
``scripts/build_mitre_kb.py``; the design decision is in
``research/notes/mitre-rag-decision.md``):

- ``kb_meta.json``  pinned provenance (ATT&CK version, source commit, date)
- ``rows.json``     field-pruned rows for all 709 live patterns (level a)
- ``index.txt``     "T-ID Name" lines with a version header (level c)
- ``aliases.json``  old->new renumber map (graders string-match old ids)
- ``cheats.jsonl``  pinned LLM-distilled cheat rows (level b)

Search order (per the decision record): technique-ID substring match
first (renumbered old ids resolve via the alias map), BM25 fallback over
the cheat corpus. Output is char-capped. Read-only by construction: the
engine only ever opens KB files for reading.
"""

from __future__ import annotations

import json
import math
import re
import threading
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

KB_DIR = Path(__file__).resolve().parent / "kb"

#: Technique id tokens inside a query (e.g. "T1003.003", "T1562.001").
TID_RE = re.compile(r"T\d{4}(?:\.\d{3})?")

#: Top-K rows per search.
TOP_K = 5

#: Default char cap on the rendered tool result (config: tools.mitre_kb).
DEFAULT_MAX_OUTPUT = 8000

#: BM25 tuning (standard defaults for a small corpus).
_K1 = 1.5
_B = 0.75

#: Tiny stopword set for the cheat-corpus BM25 (the cheats are
#: indicator-dense; over-stemming would hurt more than it helps).
_STOPWORDS = frozenset({
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "in",
    "is", "it", "may", "of", "on", "or", "that", "the", "this", "to", "use",
    "used", "using", "via", "with",
})


def _tokenize(text: str) -> list[str]:
    return [
        t for t in re.findall(r"[a-z0-9]+", text.lower())
        if t not in _STOPWORDS
    ]


@dataclass(frozen=True)
class Hit:
    """One matched technique: id, name, and either a cheat or a row."""

    id: str
    name: str
    parent_name: str | None
    cheat: str | None
    row: dict | None
    via_alias_of: str | None  # old id that resolved to this technique


class MitreKB:
    """Loaded KB: rows + aliases + cheats and a small BM25 index."""

    def __init__(self, kb_dir: Path) -> None:
        self.kb_dir = kb_dir
        meta = json.loads((kb_dir / "kb_meta.json").read_text(encoding="utf-8"))
        self.version = meta["attack_version"]
        self.live_patterns = meta["live_patterns"]
        self.rows: dict[str, dict] = json.loads(
            (kb_dir / "rows.json").read_text(encoding="utf-8")
        )
        self.aliases: dict[str, str] = json.loads(
            (kb_dir / "aliases.json").read_text(encoding="utf-8")
        )
        self.cheats: dict[str, str] = {}
        for line in (kb_dir / "cheats.jsonl").read_text(encoding="utf-8").splitlines():
            c = json.loads(line)
            self.cheats[c["id"]] = c["cheat"]
        self._index()

    def _index(self) -> None:
        """Build the BM25 statistics over the cheat corpus."""
        self._doc_terms: list[dict[str, int]] = []
        self._doc_len: list[int] = []
        df: dict[str, int] = {}
        for tid in self.rows:  # rows order = bundle order: stable
            # name weighted twice: it is the strongest identity signal
            text = (
                f"{tid} {self.rows[tid]['name']} {self.rows[tid]['name']} "
                f"{self.cheats.get(tid, '')}"
            )
            terms = _tokenize(text)
            tf: dict[str, int] = {}
            for t in terms:
                tf[t] = tf.get(t, 0) + 1
            self._doc_terms.append(tf)
            self._doc_len.append(len(terms))
            for t in tf:
                df[t] = df.get(t, 0) + 1
        self._df = df
        self._avgdl = sum(self._doc_len) / len(self._doc_len) if self._doc_len else 0.0
        self._n = len(self._doc_terms)

    # -- id resolution ----------------------------------------------------

    def resolve_tid(self, tid: str) -> tuple[str, str | None]:
        """Resolve a (possibly old) technique id to a live row id.

        Returns ``(live_id, old_id_or_None)``. Raises KeyError when the id
        is neither a live pattern nor a known alias.
        """
        if tid in self.rows:
            return tid, None
        new = self.aliases.get(tid)
        if new is not None:
            return new, tid
        raise KeyError(tid)

    # -- search -----------------------------------------------------------

    def search(self, query: str, top_k: int = TOP_K) -> tuple[str, list[Hit], list[str]]:
        """Search the KB. Returns ``(mode, hits, unknown_ids)``.

        mode: "id" (at least one technique id in the query resolved),
        "bm25" (keyword ranking), or "none" (no match at all).
        """
        found_ids: list[str] = [
            t.upper() for t in TID_RE.findall(query)
        ]
        unknown: list[str] = []
        hits: list[Hit] = []
        for tid in dict.fromkeys(found_ids):  # dedupe, keep order
            try:
                live, old = self.resolve_tid(tid)
            except KeyError:
                unknown.append(tid)
                continue
            hits.append(self._hit(live, via_alias_of=old))
        if hits:
            return "id", hits[:top_k], unknown

        scores = self._bm25(query)
        for tid, _score in scores[:top_k]:
            hits.append(self._hit(tid))
        if hits:
            return "bm25", hits, unknown
        return "none", [], unknown

    def _hit(self, tid: str, via_alias_of: str | None = None) -> Hit:
        row = self.rows[tid]
        parent_name = (
            self.rows[row["parent"]]["name"] if row["parent"] in self.rows else None
        )
        return Hit(
            id=tid,
            name=row["name"],
            parent_name=parent_name,
            cheat=self.cheats.get(tid),
            row=row,
            via_alias_of=via_alias_of,
        )

    def _bm25(self, query: str) -> list[tuple[str, float]]:
        q = _tokenize(query)
        if not q:
            return []
        scores: list[tuple[str, float]] = []
        for i, tf in enumerate(self._doc_terms):
            score = 0.0
            for term in dict.fromkeys(q):
                f = tf.get(term)
                if not f:
                    continue
                d = self._df.get(term, 0)
                idf = math.log(1 + (self._n - d + 0.5) / (d + 0.5))
                denom = f + _K1 * (1 - _B + _B * self._doc_len[i] / self._avgdl)
                score += idf * f * (_K1 + 1) / denom
            if score > 0:
                scores.append((list(self.rows)[i], score))
        scores.sort(key=lambda p: (-p[1], p[0]))
        return scores

    # -- rendering --------------------------------------------------------

    def render(
        self,
        mode: str,
        hits: list[Hit],
        unknown: Iterable[str],
        *,
        full: bool = False,
        max_output: int = DEFAULT_MAX_OUTPUT,
    ) -> str:
        """Render hits as tool output within the char cap.

        Drops trailing hits (never below one) to honor the cap.
        """
        header = f"MITRE ATT&CK KB v{self.version} ({self.live_patterns} patterns)"
        if mode == "none":
            text = (f"{header}: no match. Try a T-ID or the observed "
                    "indicators (tools, paths, API names, ports).")
        else:
            how = "by technique id" if mode == "id" else "by keywords"
            lead = f"{header} — {len(hits)} match(es) {how}:"
            rendered = [_render_hit(h, full=full) for h in hits]
            while (
                len(lead) + 2 + sum(len(b) + 2 for b in rendered) > max_output
                and len(rendered) > 1
            ):
                rendered.pop()
            dropped = len(hits) - len(rendered)
            if dropped > 0:  # the lead carries the note (survives the clamp)
                lead = (
                    f"{header} — {len(hits)} match(es) {how} "
                    f"(showing {len(rendered)}, {dropped} omitted by char cap; "
                    "re-query with a more specific term or T-ID):"
                )
            text = "\n\n".join([lead] + rendered)
        if unknown:
            text = (
                f"{text}\nNote: {', '.join(unknown)} not found — not a v"
                f"{self.version} technique id and no alias maps it "
                "(do not report ids outside the KB index)."
            )
        if len(text) > max_output:  # a single long full-mode description
            text = text[: max_output - 1] + "…"
        return text


def _render_hit(h: Hit, *, full: bool) -> str:
    parent = f" (under {h.id.split('.')[0]} {h.parent_name})" \
        if h.parent_name else ""
    head = f"{h.id} {h.name}{parent}"
    if h.via_alias_of:
        head += f"  [alias: {h.via_alias_of} -> {h.id} (renumbered)]"
    if full and h.row is not None:
        parts = [head, f"  description: {h.row['description'].strip()}"]
        if h.row.get("tactics"):
            parts.append(f"  tactics: {', '.join(h.row['tactics'])}")
        if h.row.get("platforms"):
            parts.append(f"  platforms: {', '.join(h.row['platforms'])}")
        if h.cheat:
            parts.append(f"  cheat: {h.cheat}")
        return "\n".join(parts)
    cheat = h.cheat or "(no cheat row)"
    return f"{head}\n  cheat: {cheat}"


# ---------------------------------------------------------------------------
# lazy load (shared between the tool and the prompt prefix)
# ---------------------------------------------------------------------------

_KB: MitreKB | None = None
_KB_LOCK = threading.Lock()


def get_kb(kb_dir: Path = KB_DIR) -> MitreKB:
    """Load the KB once per process (the files are small and static)."""
    global _KB
    if _KB is None:
        with _KB_LOCK:
            if _KB is None:
                _KB = MitreKB(kb_dir)
    return _KB


def reset_kb_cache() -> None:
    """Drop the cached KB (tests only)."""
    global _KB
    with _KB_LOCK:
        _KB = None


def kb_prefix(kb_dir: Path = KB_DIR) -> str:
    """The stable prompt prefix for the +mitre-kb arm.

    Index (all 709 T-IDs) + the old->new alias map + the alias-echo
    reminder. Static content: KV-cache friendly (the survey's A2 design).
    """
    kb = get_kb(kb_dir)
    index = (kb_dir / "index.txt").read_text(encoding="utf-8").strip("\n")
    alias_lines = "\n".join(f"{old} -> {kb.aliases[old]}" for old in sorted(kb.aliases))
    return "\n".join(
        [
            "MITRE ATT&CK knowledge base (pinned; details via the mitre_kb tool):",
            "- The full technique index and the old->new alias map are below. "
            "Reporters/graders may string-match an OLD technique id: when the "
            "evidence maps to a renumbered technique, report the old id the "
            "alias map points to (e.g. T1562.001 -> T1685).",
            "- mitre_kb(query=\"...\") returns top-5 cheat-sheet rows; "
            "mitre_kb(query=\"...\", full=true) returns verbatim ATT&CK "
            "descriptions (more tokens, higher fidelity).",
            "- Alias map (old -> new):",
            alias_lines,
            "- Technique index:",
            index,
        ]
    )
