#!/usr/bin/env python3
"""Build the MITRE ATT&CK KB artifact for the +mitre-kb arm (dev-time).

Per the decision record (research/notes/mitre-rag-decision.md), the KB is:

- rows.json    field-pruned rows {id, name, description, tactics,
               platforms, is_subtechnique, parent, deprecated} for all
               709 live Enterprise patterns, derived deterministically
               from the pinned STIX bundle (the (a) level)
- index.txt    "T-ID Name" lines for all 709 patterns with a one-line
               version header (the (c) level; stable prompt prefix)
- aliases.json old->new renumber map (revoked ID -> live ID with the
               same name); graders string-match old IDs, so the KB must
               answer both forms
- cheats.jsonl LLM-distilled one-row-per-technique cheat sheet (the (b)
               level), a pinned generated artifact copied verbatim from
               the dev-time distillation (never regenerated by this
               script; the script never calls an LLM)
- expansion.jsonl pinned LLM-generated incident-report paraphrases
               (issue #94), one row per pattern; built by
               scripts/expand_kb.py (prompt v1), copied verbatim like
               the cheat sheet (the script never calls an LLM)
- kb_meta.json pinned provenance + per-file sizes/hashes

Usage:
    python3 scripts/build_mitre_kb.py --stix <pinned-bundle> \
        --cheats <pinned-cheat-jsonl> --expansion <pinned-expansion-jsonl>
        [--out agent/shlepa_agent/kb]
    python3 scripts/build_mitre_kb.py --stix <bundle> --cheats <jsonl> \
        --expansion <jsonl> --check   # verify committed artifacts are
                                      # byte-identical

Inputs are pinned by content hash: regeneration is byte-identical while
the pinned hashes hold; an ATT&CK version bump is a scripted event that
updates the constants below plus the pinned input files, with a
diff-check of the output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

# --- Pinned inputs (version-bump event: update these + input files) ---

ATTACK_VERSION = "19.2"
SOURCE_REPO = "mitre-attack/attack-stix-data"
SOURCE_FILE = "enterprise-attack-19.2.json"
SOURCE_COMMIT = "6cda5ad8"
#: sha256 of the pinned bundle file (53,835,637 bytes).
STIX_SHA256 = (
    "dc1639caa5501d720e280cf1cbd8fbe009884a0c9b3e6e9ed9d0c25166c3d8f4"
)
#: sha256 of the pinned cheat sheet (709 rows, distilled 2026-09-03).
CHEATS_SHA256 = (
    "21cf9e7096b4a585266968f1022e891640214041789be2b91a988475bc2aede5"
)
#: sha256 of the pinned expansion artifact (709 rows, prompt v1,
#: generated 2026-09-03 by scripts/expand_kb.py; issue #94, measured GO).
EXPANSION_SHA256 = (
    "b4fe5a299045adb6169b627d52f21c0b3ea7ea19c543b27b8a19a46a259ff8ba"
)
EXPANSION_PROMPT_VERSION = 1
#: Pinned generation date of the expansion artifact (constant so
#: regeneration stays byte-identical; not the date this script runs).
EXPANSION_GENERATED = "2026-09-03"
#: Longest measured expansion text is 666 chars; fail loudly on bloat.
EXPANSION_MAX_CHARS = 700
#: Pinned generation date of the distilled cheat artifact (constant so
#: regeneration stays byte-identical; not the date this script runs).
GENERATED = "2026-09-03"
#: Decision target: ~1.40 MB total KB payload (pre-expansion); the pinned
#: expansion artifact (issue #94 GO) adds 315,891 B raw (~+96 KB zipped).
#: Keep a margin so an accidental bloat fails loudly.
TOTAL_BUDGET_B = 1_800_000
#: Live pattern count of the pinned bundle; a bump changes this and the
#: build must be reviewed consciously.
EXPECTED_LIVE = 709
#: Cheat line limits from the distillation spec (distill_cheats.py).
CHEAT_MAX_CHARS = 400
CHEAT_MAX_LINES = 3

OUT_FILES = ("rows.json", "index.txt", "aliases.json", "cheats.jsonl",
             "expansion.jsonl", "kb_meta.json")


def fail(msg: str) -> None:
    print(f"build_mitre_kb: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tid_of(o: dict) -> str | None:
    for r in o.get("external_references", []):
        if r.get("source_name") == "mitre-attack":
            return r.get("external_id")
    return None


def tactics_of(o: dict) -> list[str]:
    return sorted(
        {
            p["phase_name"]
            for p in o.get("kill_chain_phases", [])
            if p.get("kill_chain_name") == "mitre-attack"
        }
    )


def prune(o: dict) -> dict:
    t = tid_of(o)
    parent = t.split(".")[0] if "." in t else None
    return {
        "id": t,
        "name": o["name"],
        "description": o.get("description", ""),
        "tactics": tactics_of(o),
        "platforms": o.get("x_mitre_platforms", []),
        "is_subtechnique": bool(o.get("x_mitre_is_subtechnique")),
        "parent": parent,
        "deprecated": bool(o.get("x_mitre_deprecated")),
    }


def build(stix_path: Path, cheats_path: Path,
          expansion_path: Path) -> dict[str, bytes]:
    """Derive all KB files as bytes from the pinned inputs."""
    stix_bytes = stix_path.read_bytes()
    h = hashlib.sha256(stix_bytes).hexdigest()
    if h != STIX_SHA256:
        fail(
            f"{stix_path}: sha256 {h[:16]}... does not match the pinned "
            f"bundle ({STIX_SHA256[:16]}...); refusing to build from "
            "unpinned ATT&CK content"
        )
    bundle = json.loads(stix_bytes)
    objs = bundle["objects"]
    patterns = [o for o in objs
                if isinstance(o, dict) and o.get("type") == "attack-pattern"]
    live = [o for o in patterns if not o.get("revoked")]
    revoked = [o for o in patterns if o.get("revoked")]

    rows: dict[str, dict] = {}
    for o in live:  # bundle object order: stable for the pinned commit
        r = prune(o)
        if not r["id"]:
            fail(f"live pattern without a mitre-attack external_id: {o.get('id')}")
        if r["id"] in rows:
            fail(f"duplicate live pattern id {r['id']}")
        rows[r["id"]] = r
    if len(rows) != EXPECTED_LIVE:
        fail(f"expected {EXPECTED_LIVE} live patterns, found {len(rows)} "
             "(ATT&CK version bump? review the decision record first)")

    # (a) field-pruned rows, keyed by id, bundle order.
    rows_json = (json.dumps(rows, indent=1) + "\n").encode()

    # (c) names-only index with a one-line version header.
    header = (
        f"# MITRE ATT&CK Enterprise v{ATTACK_VERSION} | {len(rows)} patterns | "
        f"source: {SOURCE_REPO}@{SOURCE_COMMIT} | generated {GENERATED}"
    )
    index_lines = [header]
    for t in sorted(rows, key=lambda x: (x.split(".")[0], x)):
        index_lines.append(f"{t} {rows[t]['name']}")
    index_txt = ("\n".join(index_lines) + "\n").encode()

    # Old->new renumber map: revoked id -> the single live id with the
    # same name (same derivation as the measured aliases.json).
    by_name: dict[str, list[str]] = {}
    for r in rows.values():
        by_name.setdefault(r["name"].lower(), []).append(r["id"])
    aliases: dict[str, str] = {}
    for o in revoked:
        cur = by_name.get(o["name"].lower())
        old = tid_of(o)
        if old and cur and len(cur) == 1 and old != cur[0]:
            aliases[old] = cur[0]
    if not aliases:
        fail("no renumber aliases derived; bundle looks wrong")
    aliases_json = (json.dumps(aliases, indent=1, sort_keys=True) + "\n").encode()

    # (b) cheat sheet: pinned generated artifact, copied verbatim,
    # asserted row-by-row against the derived (a) rows.
    cheats_bytes = cheats_path.read_bytes()
    ch = hashlib.sha256(cheats_bytes).hexdigest()
    if ch != CHEATS_SHA256:
        fail(
            f"{cheats_path}: sha256 {ch[:16]}... does not match the pinned "
            f"cheat sheet ({CHEATS_SHA256[:16]}...); regeneration is a "
            "scripted version-bump event, not a routine re-run"
        )
    for i, line in enumerate(cheats_bytes.decode().splitlines(), 1):
        c = json.loads(line)
        if c["id"] not in rows:
            fail(f"cheat row {i}: unknown technique id {c['id']}")
        if c["name"] != rows[c["id"]]["name"]:
            fail(
                f"cheat row {i}: name {c['name']!r} != source "
                f"{rows[c['id']]['name']!r} (id/name must match verbatim)"
            )
        cheat = c["cheat"]
        if len(cheat) > CHEAT_MAX_CHARS:
            fail(f"cheat row {i}: {len(cheat)} chars > {CHEAT_MAX_CHARS}")
        if cheat.count(" | ") + 1 > CHEAT_MAX_LINES:
            fail(f"cheat row {i}: more than {CHEAT_MAX_LINES} lines")
    if len(cheats_bytes.decode().splitlines()) != len(rows):
        fail("cheat sheet row count != live pattern count")

    # (e) semantic expansion: pinned generated artifact (issue #94),
    # one incident-report paraphrase per pattern, appended to each doc's
    # BM25 text at runtime. Copied verbatim like the cheat sheet.
    expansion_bytes = expansion_path.read_bytes()
    ex = hashlib.sha256(expansion_bytes).hexdigest()
    if ex != EXPANSION_SHA256:
        fail(
            f"{expansion_path}: sha256 {ex[:16]}... does not match the "
            f"pinned expansion artifact ({EXPANSION_SHA256[:16]}...); "
            "regeneration is a scripted prompt/version-bump event, not a "
            "routine re-run"
        )
    exp_lines = expansion_bytes.decode().splitlines()
    for i, line in enumerate(exp_lines, 1):
        e = json.loads(line)
        if e["id"] not in rows:
            fail(f"expansion row {i}: unknown technique id {e['id']}")
        if e["v"] != EXPANSION_PROMPT_VERSION:
            fail(f"expansion row {i}: prompt version {e['v']} != "
                 f"{EXPANSION_PROMPT_VERSION} (unpinned regeneration)")
        text = e["text"]
        if not text.strip():
            fail(f"expansion row {i}: empty text")
        if len(text) > EXPANSION_MAX_CHARS:
            fail(f"expansion row {i}: {len(text)} chars > "
                 f"{EXPANSION_MAX_CHARS}")
        if re.search(r"\bT-\d{4,}\b", text):
            fail(f"expansion row {i}: technique id leaked into text")
    if len(exp_lines) != len(rows):
        fail("expansion row count != live pattern count")

    total = sum(map(len, (rows_json, index_txt, aliases_json, cheats_bytes,
                          expansion_bytes)))
    if total > TOTAL_BUDGET_B:
        fail(f"KB payload {total} B exceeds the decision budget "
             f"{TOTAL_BUDGET_B} B")

    meta = {
        "attack_version": ATTACK_VERSION,
        "source_repo": SOURCE_REPO,
        "source_file": SOURCE_FILE,
        "source_commit": SOURCE_COMMIT,
        "generated": GENERATED,
        "live_patterns": len(rows),
        "alias_entries": len(aliases),
        "expansion": {
            "generated": EXPANSION_GENERATED,
            "prompt_version": EXPANSION_PROMPT_VERSION,
        },
        "files": {
            "rows.json": {"bytes": len(rows_json),
                          "sha256": hashlib.sha256(rows_json).hexdigest()},
            "index.txt": {"bytes": len(index_txt),
                          "sha256": hashlib.sha256(index_txt).hexdigest()},
            "aliases.json": {
                "bytes": len(aliases_json),
                "sha256": hashlib.sha256(aliases_json).hexdigest(),
            },
            "cheats.jsonl": {"bytes": len(cheats_bytes), "sha256": ch},
            "expansion.jsonl": {"bytes": len(expansion_bytes), "sha256": ex},
        },
    }
    meta_json = (json.dumps(meta, indent=1, sort_keys=True) + "\n").encode()

    return {
        "rows.json": rows_json,
        "index.txt": index_txt,
        "aliases.json": aliases_json,
        "cheats.jsonl": cheats_bytes,
        "expansion.jsonl": expansion_bytes,
        "kb_meta.json": meta_json,
    }


def write_all(out_dir: Path, files: dict[str, bytes]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    total = 0
    for name, data in files.items():
        (out_dir / name).write_bytes(data)
        total += len(data)
        print(f"  {name:<14} {len(data):>10,} B  "
              f"{hashlib.sha256(data).hexdigest()[:16]}")
    print(f"  {'TOTAL':<14} {total:>10,} B  (budget {TOTAL_BUDGET_B:,} B)")


def check(out_dir: Path, files: dict[str, bytes]) -> int:
    bad = 0
    for name, data in files.items():
        p = out_dir / name
        if not p.is_file():
            print(f"  MISSING {p}")
            bad += 1
            continue
        existing = p.read_bytes()
        if existing == data:
            print(f"  OK      {name}")
        else:
            print(f"  DIFFERS {name} (committed {len(existing)} B, "
                  f"derived {len(data)} B)")
            bad += 1
    return 1 if bad else 0


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stix", required=True, type=Path,
                    help="pinned ATT&CK STIX bundle "
                         f"({SOURCE_FILE}, {SOURCE_REPO}@{SOURCE_COMMIT})")
    ap.add_argument("--cheats", required=True, type=Path,
                    help="pinned cheat sheet JSONL (709 rows)")
    ap.add_argument("--expansion", required=True, type=Path,
                    help="pinned expansion artifact JSONL (709 rows, "
                         "prompt v1, scripts/expand_kb.py)")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent
                    / "agent" / "shlepa_agent" / "kb",
                    help="output directory (default: agent/shlepa_agent/kb)")
    ap.add_argument("--check", action="store_true",
                    help="verify existing artifacts are byte-identical "
                         "instead of writing")
    args = ap.parse_args()

    if not args.stix.is_file():
        fail(f"STIX bundle not found: {args.stix} "
             f"(expected {SOURCE_FILE} from {SOURCE_REPO}@{SOURCE_COMMIT})")
    if not args.cheats.is_file():
        fail(f"cheat sheet not found: {args.cheats}")
    if not args.expansion.is_file():
        fail(f"expansion artifact not found: {args.expansion}")

    files = build(args.stix, args.cheats, args.expansion)
    if args.check:
        rc = check(args.out, files)
        print("check: " + ("OK" if rc == 0 else "FAILED"))
        sys.exit(rc)
    write_all(args.out, files)
    print(f"KB written to {args.out} "
          f"(ATT&CK Enterprise v{ATTACK_VERSION}, {SOURCE_COMMIT})")


if __name__ == "__main__":
    main()
